services:
  dazbeez:
    build: .
    ports:
      - "8100:8000"
    volumes:
      - ./src:/app/src:ro
      - ./static:/app/static:ro
    restart: unless-stopped
    networks:
      - server-net

networks:
  server-net:
    external: true
    name: server-net
