// Manual type extensions for Wrangler secrets and environment variables.
// Do NOT add these to cloudflare-env.d.ts — that file is regenerated by `wrangler types`.

// Wrangler secrets (set via `wrangler secret put`) are not emitted by typegen.
declare namespace Cloudflare {
  interface Env {
    RESEND_API_KEY: string;
  }
}
declare namespace NodeJS {
  interface ProcessEnv {
    CF_ACCESS_TEAM?: string;
    CF_ACCESS_AUD?: string;
    RECEIPTS_AUTH_USERNAME?: string;
    RECEIPTS_AUTH_PASSWORD?: string;
  }
}
