name = "dazbeez-networking-card"
compatibility_date = "2024-12-01"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "dazbeez-networking"
database_id = "REPLACE_WITH_YOUR_DATABASE_ID"
