#!/bin/bash
# Generates .env from macOS Keychain. Run this before starting the production stack.
# The generated .env is gitignored and can be deleted after the stack is running.
#
# Usage:
#   ./scripts/make-env.sh
#   ./scripts/make-env.sh && docker compose --profile production up -d --build

set -euo pipefail

KEYCHAIN_SERVICE="dazbeez-cloudflare-tunnel-token"
KEYCHAIN_ACCOUNT="$USER"
ENV_FILE="$(dirname "$0")/../.env"

echo "=== Generating .env from Keychain ==="

TOKEN="$(security find-generic-password \
  -a "$KEYCHAIN_ACCOUNT" \
  -s "$KEYCHAIN_SERVICE" \
  -w 2>/dev/null)" || {
  echo "ERROR: Token not found in Keychain."
  echo "Run setup first:"
  echo "  ./scripts/setup-keychain.sh"
  exit 1
}

cat > "$ENV_FILE" <<EOF
# Generated by scripts/make-env.sh — do not commit.
CLOUDFLARE_TUNNEL_TOKEN=${TOKEN}
EOF

echo ".env written to $ENV_FILE"
echo ""
echo "Start the production stack with:"
echo "  docker compose --profile production up -d --build"
echo ""
echo "Verify the site with:"
echo "  ./scripts/check-cloudflare-tunnel.sh dazbeez.com"
