export interface ReceiptAttendeeDirectoryEntry {
  id: number;
  company: string;
  title: string;
  name: string;
}

export const RECEIPT_ATTENDEE_DIRECTORY: ReceiptAttendeeDirectoryEntry[] = [
  { id: 1, company: "合同会社Dazbeez", title: "代表社員", name: "村上多寿子" },
  { id: 2, company: "合同会社Dazbeez", title: "代表社員", name: "クランデイビット" },
  { id: 3, company: "Manulife", title: "Program Director", name: "Murray Duke" },
  { id: 4, company: "Manulife", title: "CFO", name: "Jose Orfao" },
  { id: 5, company: "Manulife", title: "Program Manager", name: "Stefan Goetzinger" },
  { id: 6, company: "Manulife", title: "Project Manager", name: "Shashidar Shetty" },
  { id: 7, company: "Manulife", title: "Project Management Officer", name: "Maki Phillips" },
  { id: 8, company: "Manulife", title: "Cognizant Test Lead", name: "Casey Medsker" },
  { id: 9, company: "Manulife", title: "Project Governance Manager", name: "Nate Kemppainen" },
  { id: 10, company: "Manulife", title: "Project Operation Manager", name: "山岸リカ" },
  { id: 11, company: "Manulife", title: "ETS Change Manager", name: "Mizuki Gagnet" },
  { id: 12, company: "Manulife", title: "ETS Network Engineer", name: "Ferdinand Shimizu" },
  { id: 13, company: "Deloitte", title: "Program Manager", name: "Miako Chiyo" },
  { id: 14, company: "Manulife", title: "Project Finance Lead", name: "Steve Dalrymple" },
  { id: 15, company: "AIG Technologies KK", title: "Infra Project Manager", name: "Kenji Iyori" },
  { id: 16, company: "AIG Technologies KK", title: "Tech Lead", name: "奥野和美" },
  { id: 17, company: "Smart Partners", title: "President", name: "Jason De Luka" },
  { id: 18, company: "Smart Partners", title: "Administrator", name: "高橋　遥" },
  { id: 19, company: "FMP Connect KK", title: "President", name: "Stephan Kent" },
  { id: 20, company: "NN Life", title: "Project Manager", name: "Aaron Ward" },
  { id: 21, company: "Microsoft Japan KK", title: "Lead Developer", name: "Jason Mostella" },
  { id: 22, company: "Orix Insurance Japan KK", title: "Digital Transformation PM", name: "Ankit Shrimal" },
  { id: 23, company: "Paypay", title: "Business Continuity Manager", name: "Gary Binda" },
  { id: 24, company: "Asurion Japan KK", title: "Rakuten", name: "Arnash Gupta" },
  { id: 25, company: "Cognizant", title: "Application Project Manager", name: "Vinoth Rajeswaran" },
  { id: 26, company: "Mammoth Istanbul co., ltd.", title: "President", name: "Ali Tasbasi" },
  { id: 27, company: "輝心堂", title: "Owner", name: "下倉 淳介" },
  { id: 28, company: "一般社団法人ごみプロジェクト", title: "代表", name: "滝沢　秀一" },
  { id: 29, company: "Palette814", title: "Staff", name: "柴山佳世" },
  { id: 30, company: "ACkT Partners", title: "Partner 取締役", name: "千代　未亜子" },
  { id: 31, company: "PanOrient New Corporation", title: "Editorial Assistant", name: "細川　環" },
  { id: 32, company: "Deloitte Tohmatsu Consulting", title: "Manager", name: "及川　雅人" },
  { id: 33, company: "（株）パズルステージ", title: "代表取締役", name: "中田　圭" },
  { id: 34, company: "ACT Laboratoreis", title: "Test Manager", name: "David Isenga" },
  { id: 35, company: "K&H Consultation", title: "Construction Manager", name: "Luke Bossenbrook" },
  { id: 36, company: "State of Michigan", title: "Sr Software Engineer", name: "Mark Peckham" },
  { id: 37, company: "State of Michigan FOC", title: "Database Technician", name: "Mike Post" },
  { id: 38, company: "Knitty Gritty Treasures, LLC", title: "Co-Founder", name: "Martha Llewellen" },
  { id: 39, company: "Hopper Casual", title: "Sales person", name: "Grace Mayweather" },
  { id: 40, company: "MITTEN Distribution", title: "Account Manager", name: "Payton Fredericksen" },
  { id: 41, company: "Your IT Process", title: "Owner", name: "Deanna Helmlinger" },
  { id: 42, company: "It works!", title: "Independent Distributor", name: "Monica Crothers" },
  { id: 43, company: "GlobalPM", title: "Program Director", name: "Zain Chang" },
  { id: 44, company: "Creative 3D", title: "Design Director", name: "Donald Dahl" },
  { id: 45, company: "Da808Lounge", title: "Owner", name: "George Otani" },
  { id: 46, company: "Floral Image", title: "Owner", name: "Mary Reilly" },
  { id: 47, company: "FromFieldandFlower.co.uk", title: "Owner", name: "Stefano" },
  { id: 48, company: "slowfood.org.uk", title: "Ambassador", name: "Julius Fielder" },
  { id: 49, company: "Enterprise Holdings", title: "Management Assistant", name: "George Pumfrett" },
  { id: 50, company: "Enterprise Holdings", title: "Branch Manager", name: "Steven Delaney" },
  { id: 51, company: "Staniland Press", title: "Travel Writer", name: "John Staniland" },
  { id: 52, company: "Tinto", title: "Artisan Torrefacteur", name: "Luis Renteria" },
  { id: 53, company: "Culture Japon", title: "Video Producer", name: "Alizee Golfier" },
  { id: 54, company: "Schroders", title: "Investment Finance", name: "Donald Gates" },
  { id: 55, company: "Accenture", title: "Consultant", name: "Bill Reed" },
  { id: 56, company: "Computer Futures", title: "Principle Consultant", name: "Teren Smith" },
  { id: 57, company: "Hitachi Logistics", title: "Sr Consultant", name: "Glenn Page" },
  { id: 58, company: "Hitachi Logistics", title: "Sr Consultant", name: "Hiroko Page" },
  { id: 59, company: "Oshiro Models", title: "Model Engineer", name: "James Sharpe" },
  { id: 60, company: "All Nippon Airways", title: "Flight Agent", name: "Machi Sharpe" },
  { id: 61, company: "Manulife Japan", title: "Project Manager", name: "Eric Soon" },
  { id: 62, company: "Palmer", title: "Site Inspector", name: "Nathan Klan" },
  { id: 63, company: "Haslett Schools", title: "Interpreter", name: "Tara Lamacchia" },
  { id: 64, company: "森岡株式会社", title: "代表取締役", name: "森岡蘭多" },
  { id: 65, company: "Palette814", title: "Owner", name: "柴山哲也" },
  { id: 66, company: "日進ビルサービス株式会社", title: "代表取締役", name: "島　義行" },
];
